# Generated by Django 6.0.5 on 2026-05-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('sources', models.CharField(default='all', max_length=500)),
                ('limit', models.IntegerField(default=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(default='[]')),
                ('subdomains', models.TextField(default='[]')),
                ('ip_addresses', models.TextField(default='[]')),
                ('hosts', models.TextField(default='[]')),
                ('urls', models.TextField(default='[]')),
                ('asns', models.TextField(default='[]')),
                ('linkedin_users', models.TextField(default='[]')),
                ('interesting_urls', models.TextField(default='[]')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='my_app.scansession')),
            ],
        ),
    ]
